import React, { useState, useEffect } from "react";
import { useLocation, useNavigate, Link } from "react-router-dom";
import { motion, AnimatePresence } from "motion/react";
import {
  ArrowLeft,
  Sparkles,
  Save,
  Trash2,
  Plus,
  CheckCircle,
  AlertCircle,
  HelpCircle,
  BookOpen,
  Clock,
  Settings,
  ChevronRight,
  Eye,
} from "lucide-react";
import { useSaveGeneratedQuizMutation } from "../services/aiApiSlice.js";
import { QuizDifficulty } from "../../../types.js";

export const QuizPreviewPage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [saveQuiz, { isLoading: isSaving }] = useSaveGeneratedQuizMutation();

  const stateData = location.state as {
    questions?: Array<{ question: string; options: string[]; answer: string; explanation: string }>;
    topic?: string;
    difficulty?: QuizDifficulty;
  };

  // If no state data exists, guide them back
  useEffect(() => {
    if (!stateData || !stateData.questions) {
      navigate("/");
    }
  }, [stateData, navigate]);

  // Quiz Meta State
  const [title, setTitle] = useState(stateData?.topic ? `${stateData.topic} Expert Quiz` : "AI Generated Quiz");
  const [description, setDescription] = useState(
    stateData?.topic
      ? `A highly interactive assessment targeting key concepts, theories, and practical applications of ${stateData.topic}. Generated by Gemini AI.`
      : "Automated test assessment generated by Gemini AI."
  );
  const [category, setCategory] = useState(stateData?.topic || "General Study");
  const [difficulty, setDifficulty] = useState<QuizDifficulty>(stateData?.difficulty || QuizDifficulty.MEDIUM);
  const [timeLimit, setTimeLimit] = useState(stateData?.questions ? stateData.questions.length * 2 : 15);
  const [negativeMarking, setNegativeMarking] = useState(false);
  const [isPublished, setIsPublished] = useState(false);

  // Questions List State
  const [questions, setQuestions] = useState<
    Array<{ question: string; options: string[]; answer: string; explanation: string }>
  >(stateData?.questions || []);

  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Edit states for individual questions
  const handleQuestionTextChange = (qIndex: number, val: string) => {
    const updated = [...questions];
    updated[qIndex].question = val;
    setQuestions(updated);
  };

  const handleOptionChange = (qIndex: number, optIndex: number, val: string) => {
    const updated = [...questions];
    const oldOpt = updated[qIndex].options[optIndex];
    updated[qIndex].options[optIndex] = val;

    // If the old option was the correct answer, update the answer string too
    if (updated[qIndex].answer === oldOpt) {
      updated[qIndex].answer = val;
    }
    setQuestions(updated);
  };

  const handleCorrectAnswerChange = (qIndex: number, val: string) => {
    const updated = [...questions];
    updated[qIndex].answer = val;
    setQuestions(updated);
  };

  const handleExplanationChange = (qIndex: number, val: string) => {
    const updated = [...questions];
    updated[qIndex].explanation = val;
    setQuestions(updated);
  };

  const handleDeleteQuestion = (qIndex: number) => {
    if (questions.length <= 1) {
      setErrorMessage("An assessment must contain at least 1 question.");
      return;
    }
    const updated = questions.filter((_, idx) => idx !== qIndex);
    setQuestions(updated);
  };

  const handleAddQuestion = () => {
    const newQ = {
      question: "Enter question prompt here",
      options: ["Option A", "Option B", "Option C", "Option D"],
      answer: "Option A",
      explanation: "Add an explanation for the correct answer here.",
    };
    setQuestions([...questions, newQ]);
  };

  const handleSave = async () => {
    setErrorMessage(null);
    setSuccessMessage(null);

    // Safeguards
    if (!title.trim()) {
      setErrorMessage("Quiz title is required.");
      return;
    }
    if (!category.trim()) {
      setErrorMessage("Quiz category or topic is required.");
      return;
    }
    if (questions.length === 0) {
      setErrorMessage("At least one question is required.");
      return;
    }

    // Deep validation of options
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      if (!q.question.trim()) {
        setErrorMessage(`Question #${i + 1} prompt text cannot be empty.`);
        return;
      }
      const cleanedOpts = q.options.map((o) => o.trim()).filter(Boolean);
      if (cleanedOpts.length < 2) {
        setErrorMessage(`Question #${i + 1} must contain at least 2 non-empty options.`);
        return;
      }
      if (!cleanedOpts.includes(q.answer.trim())) {
        setErrorMessage(
          `Question #${i + 1} correct answer Choice must match one of its listed options exactly.`
        );
        return;
      }
    }

    try {
      const response = await saveQuiz({
        title: title.trim(),
        description: description.trim(),
        category: category.trim(),
        difficulty,
        timeLimit: Number(timeLimit) || 15,
        negativeMarking,
        questions,
        isPublished,
      }).unwrap();

      if (response.success) {
        setSuccessMessage("Assessment successfully compiled and saved to the database!");
        setTimeout(() => {
          navigate("/");
        }, 1500);
      }
    } catch (err: any) {
      console.error(err);
      setErrorMessage(
        err?.data?.message || "Failed to save generated quiz. Verify data integrity and try again."
      );
    }
  };

  if (!stateData) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 transition-colors duration-300 dark:bg-zinc-950 dark:text-zinc-50">
      {/* Upper Navigation Bar */}
      <nav className="border-b border-gray-100 bg-white px-6 py-4 dark:border-zinc-800 dark:bg-zinc-900">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <div className="flex items-center space-x-3">
            <Link
              to="/"
              className="flex h-9 w-9 items-center justify-center rounded-xl bg-gray-100 text-gray-500 hover:bg-gray-200 transition dark:bg-zinc-800 dark:text-zinc-400 dark:hover:bg-zinc-700"
            >
              <ArrowLeft className="h-4 w-4" />
            </Link>
            <div className="flex items-center space-x-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600/10 text-indigo-600 dark:bg-indigo-500/15 dark:text-indigo-400">
                <Sparkles className="h-4 w-4" />
              </div>
              <span className="font-sans text-sm font-black text-gray-400 uppercase tracking-widest">
                Staging Arena
              </span>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="flex items-center space-x-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-55 px-5 py-2.5 text-xs font-bold text-white transition shadow-sm"
            >
              {isSaving ? (
                <>
                  <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white border-t-transparent" />
                  <span>Saving...</span>
                </>
              ) : (
                <>
                  <Save className="h-3.5 w-3.5" />
                  <span>Compile & Save</span>
                </>
              )}
            </button>
          </div>
        </div>
      </nav>

      <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-12">
          {/* Left Column: Quiz Parameters Form (Config) */}
          <div className="space-y-6 lg:col-span-4">
            <div className="rounded-2xl border border-gray-100 bg-white p-6 shadow-xs dark:border-zinc-800 dark:bg-zinc-900">
              <h3 className="font-sans text-base font-black text-gray-900 dark:text-white mb-5 flex items-center space-x-2">
                <Settings className="h-4 w-4 text-indigo-500" />
                <span>Quiz Configuration</span>
              </h3>

              <div className="space-y-4">
                {/* Title */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                    Assessment Title
                  </label>
                  <input
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                    required
                  />
                </div>

                {/* Description */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                    Description / Syllabus
                  </label>
                  <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    rows={4}
                    className="w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                    required
                  />
                </div>

                {/* Category */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                    Category Stream
                  </label>
                  <input
                    type="text"
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    className="w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                    required
                  />
                </div>

                {/* Grid for parameters */}
                <div className="grid grid-cols-2 gap-4">
                  {/* Difficulty */}
                  <div className="space-y-1">
                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                      Difficulty
                    </label>
                    <select
                      value={difficulty}
                      onChange={(e) => setDifficulty(e.target.value as QuizDifficulty)}
                      className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                    >
                      <option value={QuizDifficulty.EASY}>Easy</option>
                      <option value={QuizDifficulty.MEDIUM}>Medium</option>
                      <option value={QuizDifficulty.HARD}>Hard</option>
                    </select>
                  </div>

                  {/* Time limit */}
                  <div className="space-y-1">
                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                      Duration (Mins)
                    </label>
                    <input
                      type="number"
                      value={timeLimit}
                      onChange={(e) => setTimeLimit(Number(e.target.value))}
                      className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                      min={1}
                      required
                    />
                  </div>
                </div>

                {/* Switches */}
                <div className="space-y-3 pt-2">
                  <label className="flex items-center space-x-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={negativeMarking}
                      onChange={(e) => setNegativeMarking(e.target.checked)}
                      className="h-4.5 w-4.5 rounded-sm border-gray-300 text-indigo-600 focus:ring-indigo-500 dark:border-zinc-800 dark:bg-zinc-950"
                    />
                    <div className="flex flex-col">
                      <span className="text-xs font-semibold text-gray-700 dark:text-zinc-300">
                        Negative Marking
                      </span>
                      <span className="text-[9px] text-gray-400 font-medium">
                        Deduct marks on wrong answers
                      </span>
                    </div>
                  </label>

                  <label className="flex items-center space-x-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={isPublished}
                      onChange={(e) => setIsPublished(e.target.checked)}
                      className="h-4.5 w-4.5 rounded-sm border-gray-300 text-indigo-600 focus:ring-indigo-500 dark:border-zinc-800 dark:bg-zinc-950"
                    />
                    <div className="flex flex-col">
                      <span className="text-xs font-semibold text-gray-700 dark:text-zinc-300">
                        Publish Immediately
                      </span>
                      <span className="text-[9px] text-gray-400 font-medium">
                        Make visible to student arena
                      </span>
                    </div>
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Questions Preview and Tweaking */}
          <div className="space-y-6 lg:col-span-8">
            {/* Feedback messages */}
            {errorMessage && (
              <div className="flex items-start space-x-2.5 rounded-2xl bg-red-50 p-4.5 text-sm text-red-700 dark:bg-red-950/25 dark:text-red-400 border border-red-100 dark:border-red-900/30">
                <AlertCircle className="mt-0.5 h-4.5 w-4.5 shrink-0" />
                <div>
                  <p className="font-bold text-xs">Validation Failed</p>
                  <p className="text-[11px] opacity-90 leading-relaxed mt-0.5">{errorMessage}</p>
                </div>
              </div>
            )}

            {successMessage && (
              <div className="flex items-start space-x-2.5 rounded-2xl bg-emerald-50 p-4.5 text-sm text-emerald-700 dark:bg-emerald-950/25 dark:text-emerald-400 border border-emerald-100 dark:border-emerald-900/30">
                <CheckCircle className="mt-0.5 h-4.5 w-4.5 shrink-0" />
                <div>
                  <p className="font-bold text-xs">Assessment Compiled</p>
                  <p className="text-[11px] opacity-90 leading-relaxed mt-0.5">{successMessage}</p>
                </div>
              </div>
            )}

            <div className="flex items-center justify-between mb-2">
              <div>
                <h2 className="font-sans text-lg font-black text-gray-900 dark:text-white">
                  Assessment Structure
                </h2>
                <p className="text-xs text-gray-400">
                  Review, edit options, or remove questions generated by the AI model.
                </p>
              </div>

              <button
                onClick={handleAddQuestion}
                className="flex items-center space-x-1 rounded-xl bg-gray-100 hover:bg-gray-200 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700 px-3 py-1.5 text-xs font-bold transition"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add Question</span>
              </button>
            </div>

            {/* Questions list */}
            <div className="space-y-6">
              {questions.map((q, qIndex) => (
                <div
                  key={qIndex}
                  className="rounded-3xl border border-gray-100 bg-white p-6 shadow-xs dark:border-zinc-800 dark:bg-zinc-900 relative group"
                >
                  <div className="absolute top-6 right-6 flex items-center space-x-2">
                    <span className="font-mono text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-500 dark:bg-zinc-800 dark:text-zinc-400">
                      Q#{qIndex + 1}
                    </span>
                    <button
                      onClick={() => handleDeleteQuestion(qIndex)}
                      className="rounded-lg p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-500 transition dark:hover:bg-red-950/20"
                      title="Delete Question"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>

                  {/* Question Prompt */}
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Question Text
                    </label>
                    <input
                      type="text"
                      value={q.question}
                      onChange={(e) => handleQuestionTextChange(qIndex, e.target.value)}
                      className="w-full max-w-xl rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-xs font-bold focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                    />
                  </div>

                  {/* Options Matrix */}
                  <div className="mt-5 space-y-3">
                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Option Alternatives & Correct Choice
                    </label>

                    <div className="grid gap-3 sm:grid-cols-2">
                      {q.options.map((opt, optIndex) => {
                        const isCorrect = q.answer === opt;
                        return (
                          <div
                            key={optIndex}
                            className={`flex items-center space-x-2 rounded-xl border p-2.5 transition ${
                              isCorrect
                                ? "border-indigo-200 bg-indigo-50/20 dark:border-indigo-900/40 dark:bg-indigo-950/10"
                                : "border-gray-100 dark:border-zinc-800"
                            }`}
                          >
                            <button
                              type="button"
                              onClick={() => handleCorrectAnswerChange(qIndex, opt)}
                              className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border transition ${
                                isCorrect
                                  ? "border-indigo-600 bg-indigo-600 text-white"
                                  : "border-gray-300 bg-white hover:border-gray-400 dark:border-zinc-700 dark:bg-zinc-950"
                              }`}
                            >
                              {isCorrect && <div className="h-2 w-2 rounded-full bg-white" />}
                            </button>

                            <input
                              type="text"
                              value={opt}
                              onChange={(e) => handleOptionChange(qIndex, optIndex, e.target.value)}
                              className="w-full border-none bg-transparent p-0 text-xs font-medium focus:ring-0 outline-hidden dark:text-white"
                              placeholder={`Option ${optIndex + 1}`}
                            />
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* Educational Explanation */}
                  <div className="mt-5 space-y-1.5">
                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Educational Explanation
                    </label>
                    <textarea
                      value={q.explanation}
                      onChange={(e) => handleExplanationChange(qIndex, e.target.value)}
                      rows={2}
                      className="w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10 outline-hidden transition dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                      placeholder="Add an explanation explaining why this answer choice is correct..."
                    />
                  </div>
                </div>
              ))}
            </div>

            {/* Bottom Controls */}
            <div className="flex items-center justify-between border-t border-gray-100 pt-6 dark:border-zinc-800">
              <span className="font-sans text-xs font-bold text-gray-400">
                Total Assessment Questions: {questions.length}
              </span>

              <button
                onClick={handleSave}
                disabled={isSaving}
                className="flex items-center space-x-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-55 px-6 py-3 text-xs font-bold text-white transition shadow-sm"
              >
                {isSaving ? (
                  <>
                    <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                    <span>Compiling Quiz...</span>
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4" />
                    <span>Compile & Save Quiz</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
export default QuizPreviewPage;
